---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd.git
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    incron: https://github.com/simp/pupmod-simp-incron.git
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    sssd: https://github.com/simp/pupmod-simp-sssd.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers.git
  symlinks:
    simp_openldap: "#{source_dir}"
