---
fixtures:
  symlinks:
    openldap: "#{source_dir}"
    auditd: "#{source_dir}/../auditd"
    augeasproviders_core: "#{source_dir}/../augeasproviders_core"
    augeasproviders_grub: "#{source_dir}/../augeasproviders_grub"
    common: "#{source_dir}/../common"
    concat: "#{source_dir}/../concat"
    iptables: "#{source_dir}/../iptables"
    logrotate: "#{source_dir}/../logrotate"
    nscd: "#{source_dir}/../nscd"
    pki: "#{source_dir}/../pki"
    rsync: "#{source_dir}/../rsync"
    rsyslog: "#{source_dir}/../rsyslog"
    sssd: "#{source_dir}/../sssd"
    stdlib: "#{source_dir}/../stdlib"
    tcpwrappers: "#{source_dir}/../tcpwrappers"
